language: python
python:
  - "3.7"
install:
  - pip install .
  - pip install pytest
  - pip install codecov
  - pip install pytest-cov

script:
  - pytest --cov=ferro
  - coverage run --source=ferro/ tests/lcmTest.py
  - coverage run --source=ferro/ tests/forcDomainTest.py
  - coverage run --source=ferro/ tests/fftTestRTWhite.py
  - coverage run --source=ferro/ tests/a0CalcTest.py
  - coverage run --source=ferro/ tests/test_aixacct.py
  - coverage run --source=ferro/ bin/FeFETD1_cComparison.py
  - coverage run --source=ferro/ bin/forc_comparison.py
  - coverage run --source=ferro/ bin/hfo2_mfm.py
  - coverage run --source=ferro/ bin/multidomainAnalysis.py
  

after_success:
  - codecov
