language: python
python:
  - "3.6"
install:
  - pip install .
  - pip install codecov

script:
  - coverage run --source=ferro/ tests/lcmTest.py
  - coverage run --source=ferro/ tests/forcDomainTest.py
  - coverage run --source=ferro/ tests/fftTestRTWhite.py
  - coverage run --source=ferro/ tests/a0CalcTest.py

after_success:
  - codecov