language: python
python:
  - "3.7"
install:
  - pip install .
  - pip install pytest
  - pip install codecov
  - pip install -r tutorial/tut-requirements.txt

script: 
  - jupytext --sync tutorial/pyscript/*.py
  - jupytext --execute tutorial/*.ipynb
  - coverage run --source=ferro/ -m py.test
  - coverage run --append --source=ferro/ tests/lcmTest.py
  - coverage run --append --source=ferro/ tests/forcDomainTest.py
  - coverage run --append --source=ferro/ tests/fftTestRTWhite.py
  - coverage run --append --source=ferro/ tests/a0CalcTest.py
  - coverage run --append --source=ferro/ tests/test_aixacct.py
  - coverage run --append --source=ferro/ bin/FeFETD1_cComparison.py
  - coverage run --append --source=ferro/ bin/forc_comparison.py
  - coverage run --append --source=ferro/ bin/hfo2_mfm.py
  - coverage run --append --source=ferro/ bin/multidomainAnalysis.py
  - coverage run --append --source=ferro/ tutorial/pyscript/1-Data_Import.py
  - coverage run --append --source=ferro/ tutorial/pyscript/2-Data_Visualization.py


after_success:
  - codecov
