language: python
python:
  - "3.6"
install:
  - pip install .
  - pip install pytest
  - pip install codecov

script:
  - cd ferro
  - coverage run  tests/lcmTest.py
  - coverage run  tests/forcDomainTest.py
  - coverage run  tests/fftTestRTWhite.py
  - coverage run  tests/a0CalcTest.py
  - coverage run  tests/test_aixacct.py
  - coverage run  bin/FeFETD1_cComparison.py
  - coverage run  bin/forc_comparison.py
  - coverage run  bin/hfo2_mfm.py
  - coverage run  bin/multidomainAnalysis.py
  - pytest

after_success:
  - codecov